### PR TITLE
Fix: Fixes theme picker to work as expected on mobile phones

### LINKED ISSUE #237: [Bug] Theme switcher is broken on mobile
Maybe refactor using https://markdotto.com/2022/03/10/horizontal-scrolling-nav/ as a base?

### PR DESCRIPTION
**Pull request by MaNemoj01**
Fixes theme picker for mobile phone.

Tested on my Pixel 4a
Recorded preview on Google Chrome console responsive

Resolves #237 

## Preview

https://user-images.githubusercontent.com/44163914/223775481-fab212bb-7457-4ab8-85c6-5545430f9143.mov

### CODE REVIEW

**Comment by carbontwelve** [comment]
@MaNemoj01 thank you, i'll review this soon and get it merged in if I can't break it :D

**Comment by MaNemoj01** [comment]
Aweomse please find an innovative way to break it so I can dig deeper to fix whatever you break :D

**Comment by MaNemoj01** [comment]
@carbontwelve bump for review :D

**Comment by carbontwelve** [comment]
@MaNemoj01 thank you for this, appologies for taking so long to merge its been a busy few months.

**Comment by MaNemoj01** [comment]
No worries glad I could help out @carbontwelve  😄

**Pull request merged**
